@EmailMicroService_HostAddress = http://localhost:5238

GET {{EmailMicroService_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{EmailMicroService_HostAddress}}/email/send
Content-Type: application/json

{
  "from": "sender@example.com",
  "to": "recipient@example.com",
  "subject": "Hello",
  "body": "<p>Hello from EmailMicroService</p>"
}

###
